version: "3.8"
services:
  metahkg-redirect:
    image: registry.gitlab.com/metahkg/metahkg-redirect/${branch:-dev}:${version:-latest}
    container_name: metahkg-redirect
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        env: ${env}
    tty: true
    restart: always
    environment:
      PORT: ${PORT:-3000}
      SAFEBROWSING_API_KEY: ${SAFEBROWSING_API_KEY}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:${MONGO_PORT:-27017}
      REDIS_HOST: metahkg-redirect-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      env: ${env}
      HMAC_KEY: ${HMAC_KEY}
      HMAC_VERIFY: ${HMAC_VERIFY}
    mem_limit: 500mb
    memswap_limit: 500mb
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    networks:
      - metahkg-redirect-network
    volumes:
      - ../.next:/app/.next
      - ../src:/app/src
      - ../public:/app/public
  redis:
    image: redis:alpine
    container_name: metahkg-redirect-redis
    command: redis-server --save 10 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: always
    mem_limit: 2gb
    memswap_limit: 2gb
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - metahkg-redirect-network
    volumes:
      - ./redis_data:/data
  mongo:
    image: ${MONGO_IMAGE:-mongo:6.0}
    container_name: mongo
    command: mongod --auth --port=${MONGO_PORT:-27017} --bind_ip_all
    restart: always
    mem_limit: 500mb
    memswap_limit: 500mb
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: metahkg-redirect
    networks:
      - metahkg-redirect-network
    volumes:
      - ./mongo_data:/data/db
networks:
  metahkg-redirect-network:
    driver: bridge
